language: java

jdk: openjdk7

sudo: false

before_script:
  - set -e
  - cd $TRAVIS_BUILD_DIR
  - JAR=antlr-4.5.2-complete.jar
  - curl -O http://www.antlr.org/download/$JAR
  - export CLASSPATH=./$JAR:"$CLASSPATH"

script: make test
